akirayorunoe/doan

client/src/App.js
client/src/components/Policy/Text.js
client/src/containers/Policy.js
client/src/styles/components/Policy/Text.css

Nhanhcuakhangpro123456

---

client/src/components/General/Cart.js
client/src/components/General/Nav.js
client/src/components/Home/cardList/Cardlist.js
client/src/components/SignUp/SignUp.js
client/src/styles/components/General/Cart.css
client/src/styles/components/General/Nav.css
client/src/styles/components/Home/Card.css
client/src/styles/components/Home/Cardlist.css
client/src/styles/components/SignUp/SignUp.css

Cái cart k thấy đường,có gì sửa hộ,mới làm cái form th

fix vo anh,fix cardlist,lam cai' card tam.

---

client/src/components/SignUp/SignUp.js
client/src/styles/components/Home/HotBar.css
client/src/styles/components/SignUp/SignUp.css

fix khương boi level maxxxxxxxxxxxxxxxxxxxx

fixkhuongboimaxlvl

---

client/src/App.js
client/src/components/Forget_pass/Forget_pass.js
client/src/components/General/Form.js
client/src/containers/ForgetPass.js
client/src/styles/components/ForgetPass/textForgetpass.css

addForgetPass

---

client/src/App.js
client/src/components/Home/HotBar.js
client/src/components/Policy/Text.js
client/src/components/Product/ProductImg.js
client/src/containers/Product.js
client/src/styles/components/About/hero.css
client/src/styles/components/ForgetPass/textForgetpass.css
client/src/styles/components/Home/HotBar.css
client/src/styles/components/Policy/Text.css
client/src/styles/components/Product/ProductImg.css
client/src/styles/components/SignUp/SignUp.css
client/src/styles/containers/Product.css

fix 1 đống lỗi giao diện từ chụy vân đến ku khang r qua thằng ku nhựt <("), có thêm đc cái ảnh trang product!

fix1dongthu

---

client/src/App.js
client/src/components/Home/cardList/Cardlist.js
client/src/components/Product/ProductList.js
client/src/components/Product/Sort.js
client/src/containers/Product.js
client/src/styles/components/Home/Card.css
client/src/styles/components/Home/Cardlist.css
client/src/styles/components/Product/ProductList.css
client/src/styles/components/Product/Sort.css
client/src/styles/containers/Product.css

add tạm trang product còn sửa sau

addProductTam

---

client/src/App.css
client/src/components/Home/cardList/Cardlist.js
client/src/styles/components/About/info.css
client/src/styles/components/General/Header.css
client/src/styles/components/General/Nav.css
client/src/styles/components/Home/BgHeader.css
client/src/styles/components/Home/Cardlist.css
client/src/styles/components/Home/Circle.css
client/src/styles/components/Home/HotList.css
client/src/styles/containers/About/About.css
client/src/styles/containers/Home.css

fixResponsive

---

client/src/App.js
client/src/components/Home/cardList/Card.js
client/src/components/Home/cardList/Cardlist.js
client/src/components/Home/cardList/HotList.js
client/src/containers/Product.js
client/src/styles/components/Home/Card.css
client/src/styles/components/Home/Cardlist.css
client/src/styles/components/Home/HotList.css
client/src/styles/containers/Product.css

fix product

---

client/src/App.css
client/src/App.js
client/src/components/Home/cardList/Cardlist.js
client/src/components/Home/cardList/HotList.js
client/src/components/Product/ProductInfo.js
client/src/components/Product/ProductList.js
client/src/styles/components/General/Footer/Footer.css
client/src/styles/components/Home/BgHeader.css
client/src/styles/components/Home/Card.css
client/src/styles/components/Home/Cardlist.css
client/src/styles/components/Home/HotList.css
client/src/styles/components/Product/ProductInfo.css
client/src/styles/components/Product/ProductList.css

add productInfo + navigate info

addProductInfoTest

---

client/src/styles/components/Product/ProductInfo.css

dmbanhoang

---

client/src/components/Home/cardList/Cardlist.js
client/src/components/Product/ProductInfo.js
client/src/components/Product/Sort.js
client/src/components/SignUp/SignUp.js

add address and phonenum with productinfo id

fixProductInfo

---

client/src/components/Product/ProductCard.js
client/src/components/Product/QuantitiesButton.js
client/src/styles/components/Product/ProductCard.css
client/src/styles/components/Product/QuantitiesButton.css

add quantitiesBtn and styles productInfo

addQuantitiesBtn

---

client/src/components/General/Cart.js
client/src/components/Home/cardList/Cardlist.js
client/src/components/Home/cardList/HotList.js
client/src/components/Product/Pagination/Pagination.js
client/src/styles/components/General/Cart.css
client/src/styles/components/General/Nav.css
client/src/styles/components/Product/ProductImg.css

pushchohoang

---

client/src/App.js
client/src/components/General/Header.js
client/src/containers/UserPage.js

addUserPage

---

client/src/App.css
client/src/containers/UserPage.js
client/src/styles/components/About/hero.css
client/src/styles/components/General/Header.css
client/src/styles/containers/User.css

fix some style

---

client/src/containers/SearchPage.js
client/src/styles/components/Home/Card.css
client/src/styles/containers/SearchPage.css

fix search result

---

client/src/styles/components/General/Cart.css

fix res cart

---

client/public/index.html
client/src/App.css
client/src/components/Home/CircleWrapper.js
client/src/components/Home/HotBar.js
client/src/components/Home/cardList/Cardlist.js
client/src/components/Product/Pagination/Pagination.js
client/src/components/Product/ProductList.js
client/src/containers/Product.js
client/src/styles/components/Home/BgHeader.css
client/src/styles/components/Home/Circle.css
client/src/styles/components/Home/CircleWrapper.css
client/src/styles/components/Home/HotBar.css
client/src/styles/components/Product/Pagination.css
client/src/styles/components/Product/ProductList.css
client/src/styles/components/Product/Sort.css
client/src/styles/containers/Home.css
client/src/styles/containers/Product.css

fix UI product

---

client/src/components/Home/cardList/Cardlist.js
client/src/components/Home/cardList/HotList.js
client/src/components/Product/ProductCard.js
client/src/components/Product/QuantitiesButton.js
client/src/styles/components/Home/Card.css
client/src/styles/components/Product/ProductCard.css
client/src/styles/components/Product/ProductInfo.css
client/src/styles/components/Product/QuantitiesButton.css

style info

---

client/src/components/Product/ProductImg.js
client/src/components/Product/ProductInfo.js
client/src/styles/components/Product/Pagination.css
client/src/styles/components/Product/ProductImg.css
client/src/styles/components/Product/ProductInfo.css

fix style UI bg product

---

client/src/components/General/footer.js

add social link icon
